default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: akarsutrade_development

test:
  <<: *default
  database: akarsutrade_test

production:
  <<: *default
  database: akarsutrade_production
  username: akarsutrade
  password: <%= ENV['STG_HR_SYSTEM_DATABASE_PASSWORD'] %>